export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";

export const FETCH_POSTSEARCH_REQUEST = "FETCH_POSTSEARCH_REQUEST";
export const FETCH_POSTSEARCH_SUCCESS = "FETCH_POSTSEARCH_SUCCESS";
export const FETCH_POSTSEARCH_ERROR = "FETCH_POSTSEARCH_ERROR";

export const FETCH_FILTERCATEGORIES_REQUEST = "FETCH_FILTERCATEGORIES_REQUEST";
export const FETCH_FILTERCATEGORIES_SUCCESS = "FETCH_FILTERCATEGORIES_SUCCESS";
export const FETCH_FILTERCATEGORIES_ERROR = "FETCH_FILTERCATEGORIES_ERROR";

export const FETCH_FILTERINGPOSTS_REQUEST = "FETCH_FILTERINGPOSTS_REQUEST";
export const FETCH_FILTERINGPOSTS_SUCCESS = "FETCH_FILTERINGPOSTS_SUCCESS";
export const FETCH_FILTERINGPOSTS_ERROR = "FETCH_FILTERINGPOSTS_ERROR";

export const FETCH_FILTERINGCATEGORIES_REQUEST =
  "FETCH_FILTERINGCATEGORIES_REQUEST";

export const FETCH_FILTERINGCATEGORIES_SUCCESS =
  "FETCH_FILTERINGCATEGORIES_SUCCESS";

export const FETCH_FILTERINGCATEGORIES_ERROR =
  "FETCCH_FILTERINGCATEGORIES_ERROR";

export const FETCH_FILTERINGUSERS_REQUEST = "FETCH_FILTERINGUSERS_REQUEST";
export const FETCH_FILTERINGUSERS_SUCCESS = "FETCH_FILTERINGUSERS_SUCCESS";
export const FETCH_FILTERINGUSERS_ERROR = "FETCH_FILTERINGUSERS_ERROR";

export const FETCH_EDITPOSTS_REQUEST = "FETCH_EDITPOSTS_REQUEST";
export const FETCH_EDITPOSTS_SUCCESS = "FETCH_EDITPOSTS_SUCCESS";
export const FETCH_EDITPOSTS_ERROR = "FETCH_EDITPOSTS_ERROR";

export const FETCH_POSTSTATUSFILTER_REQUEST = "FETCH_POSTSTATUSFILTER_REQUEST";
export const FETCH_POSTSTATUSFILTER_SUCCESS = "FETCH_POSTSTATUSFILTER_SUCCESS";
export const FETCH_POSTSTATUSFILTER_ERROR = "FETCH_POSTSTATUSFILTER_ERROR";

export const FETCH_ALLPOSTS_REQUEST = "FETCH_ALLPOSTS_REQUEST";
export const FETCH_ALLPOSTS_SUCCESS = "FETCH_ALLPOSTS_SUCCESS";
export const FETCH_ALLPOSTS_ERROR = "FETCH_ALLPOSTS_ERROR";

export const USER_FILTERSTATUS_REQUEST = "USER_FILTERSTATUS_REQUEST";
export const USER_FILTERSTATUS_SUCCESS = "USER_FILTERSTATUS_SUCCESS";
export const USER_FILTERSTATUS_ERROR = "USER_FILTERSTATUS_ERROR";

export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";

export const FETCH_POSTPAGINATION_REQUEST = "FETCH_POSTPAGINATION_REQUEST";
export const FETCH_POSTPAGINATION_SUCCESS = "FETCH_POSTPAGINATION_SUCCESS";
export const FETCH_POSTPAGINATION_ERROR = "FETCH_POSTPAGINATION_ERROR";

export const PAGINATION_CATEGORIES_REQUEST = "PAGINATION_CATEGORIES_REQUEST";
export const PAGINATION_CATEGORIES_SUCCESS = "PAGINATION_CATEGORIES_SUCCESS";
export const PAGINATION_CATEGORIES_ERROR = "PAGINATION_CATEGORIES_ERROR";

export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_ERROR = "ADD_POST_ERROR";

export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const CATEGORY_CHANGE_REQUEST = "CATEGORY_CHANGE_REQUEST";
export const CATEGORY_CHANGE_SUCCESS = "CATEGORY_CHANGE_SUCCESS";
export const CATEGORY_CHANGE_ERROR = "CATEGORY_CHANGE_ERROR";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_ERROR = "CATEGORY_DELETE_ERROR";

export const CATEGORY_SEARCH_REQUEST = "CATEGORY_SEARCH_REQUEST";
export const CATEGORY_SEARCH_SUCCESS = "CATEGORY_SEARCH_SUCCESS";
export const CATEGORY_SEARCH_ERROR = "CATEGORY_SEARCH_ERROR";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";

export const USER_CHANGE_REQUEST = "USER_CHANGE_REQUEST";
export const USER_CHANGE_SUCCESS = "USER_CHANGE_SUCCESS";
export const USER_CHANGE_ERROR = "USER_CHANGE_ERROR";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_ERROR = "USER_SEARCH_ERROR";

export const USER_ROLE_REQUEST = "USER_ROLE_REQUEST";
export const USER_ROLE_SUCCESS = "USER_ROLE_SUCCESS";
export const USER_ROLE_ERROR = "USER_ROLE_ERROR";

export const USER_PAGINATION_REQUEST = "USER_PAGINATION_REQUEST";
export const USER_PAGINATION_SUCCESS = "USER_PAGINATION_SUCCESS";
export const USER_PAGINATION_ERROR = "USER_PAGINATION_ERROR";

export const USER_ADD_REQUEST = "USER_ADD_REQUEST";
export const USER_ADD_SUCCESS = "USER_ADD_SUCCESS";
export const USER_ADD_ERROR = "USER_ADD_ERROR";
